export {useGetTours} from "./getTours.ts"
export {useGetTour} from "./getTour.ts"
export {usePostTour} from "./postTour.ts"
export {useDeleteTour} from "./deleteTour.ts"
export {useGetFilteredTours} from "./getFilteredTours.ts"
export {useGetSortedTours} from "./getSortedTours.ts"